### ISSUE TITLE
Definir paleta de cores

### ISSUE THREAD

**Issue by hcalmeida-uesc** [hcalmeida-uesc/relatos-sinform-erbase#3]

**Comment by wesleyfn** [comment]
Paleta de cores como variáveis CSS:
```css
:root {
  --content-bg-color: #fdfdfd;
  --body-bg-color: #f5f7fa;
  --btn-bg-color: #0d6efd;
  --btn-hover-color: #0b5ed7;
  --btn-p-color: #fdfdfd;
  --hx-base-color: #4d4d4d;
  --p-base-color: #717171;
  --p-desc-color: #b5b5c3;
}
```
